name: build
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic
    
    steps:
    - name: non-ros-deps
      run: |
        sudo apt-get update
        sudo apt-get install -y git cmake wget libyaml-cpp-dev qt5-default \
          libopencv-dev libopencv-videoio-dev python3-vcstool
    - name: ros-workspace
      run: |
        cd /home/
        mkdir -p rmf_demos_ws/src
    - name: checkout
      shell: bash
      run: |
        cd /home/rmf_demos_ws/src
        git checkout "${GITHUB_REF:11}"
    - name: build
      shell: bash
      run: |
        cd /home/rmf_demos_ws/src
        source /opt/ros/eloquent/setup.bash
        colcon build
