name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: deps
      run: |
        sudo apt install libyaml-cpp-dev
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make
      run: |
        cd build
        make
